CREATE SEQUENCE andress_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE andress (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE andress_id_seq PRIMARY KEY,
  street VARCHAR(255),
  number INT,
  complement VARCHAR(255),
  district VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(2),
  id_customer BIGINT NOT NULL,
  FOREIGN KEY (id_customer) REFERENCES customer(id)
);